services:
  - type: web
    name: ğ‹ğğ‘ğƒ_ğğğˆğ“ğ_ğ“ğ„ğ‚ğ‡-ğğ€ğˆğ‘
    env: docker
    plan: free
    branch: main
    repo: https://github.com/LORD-OBITO-DEV/LORD_OBITO-MD
    dockerfilePath: ./Dockerfile
    autoDeploy: true
